### ISSUE TITLE
Error: Unity Ads SDK failed to initialize due to previous failed reason

### ISSUE THREAD

**Issue by n0xgg04** [nahooni0511/react-native-unity-ads-monetization#1]
When i tried to initialize,i it failed with error: "Error: Unity Ads SDK failed to initialize due to previous failed reason `new NativeEventEmitter()` was called with a non-null argument without the required `addListener` method.
 WARN  `new NativeEventEmitter()` was called with a non-null argument without the required `removeListeners` method."
 
 Please help me. Thanks

**Comment by n0xgg04** [comment]
Error when load ads: "adMarkup is missing; objectId is missing"

**Comment by nahooni0511** [comment]
It appears this issue may be related to the configuration of Unity Ads rather than a problem with the react-native-unity-ads-monetization codebase. For guidance on properly setting up Unity Ads, especially regarding ad markup and object ID errors, please refer to this Unity forum thread for potential solutions and advice: https://forum.unity.com/threads/unity-ads-problems.1444789/
